SELECT "ZFULLNUMBER", "ZADDRESS" FROM "ZABCDPHONENUMBER" INNER JOIN "ZABCDEMAILADDRESS" ON "ZABCDPHONENUMBER"."ZOWNER" = "ZABCDEMAILADDRESS"."ZOWNER" WHERE "ZABCDPHONENUMBER"."ZOWNER" = (
    SELECT "Z_PK" FROM "ZABCDRECORD" WHERE lower(trim(ifnull("ZFIRSTNAME", '') || ' ' || ifnull("ZLASTNAME", ''))) = lower(:contact_name)
);
