SELECT "ZFULLNUMBER", "ZADDRESS" FROM "ZABCDPHONENUMBER" INNER JOIN "ZABCDEMAILADDRESS" ON "ZABCDPHONENUMBER"."ZOWNER" = "ZABCDEMAILADDRESS"."ZOWNER" WHERE "ZABCDPHONENUMBER"."ZOWNER" = (
    SELECT "Z_PK" FROM "ZABCDRECORD" WHERE trim("ZFIRSTNAME" || ' ' || "ZLASTNAME") = :contact_name
);
