# This workflow will install project dependencies and run all tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3


    - name: Check sqlite3 version (pre-upgrade)
      run: sqlite3 --version

    # The ubuntu-latest runner for GitHub Actions (currently 22.04) uses a
    # version of sqlite3 which lacks support for FULL OUTER JOIN, a feature
    # required by one of my SQL queries. In an attempt to fix this, we will try
    # upgrading sqlite3 as part of the action (prior to running tests). For more
    # details, see:
    # <https://github.com/actions/runner-images/issues/9033#issuecomment-1857780470>
    - name: Upgrade sqlite3
      run: |
        download_link="https://www.sqlite.org/2023/sqlite-tools-linux-x64-3440200.zip"
        wget "$download_link" -P /tmp
        unzip "/tmp/$(basename "$download_link")" -d /tmp
        sudo install /tmp/sqlite3 /usr/local/bin/

    - name: Check sqlite3 version (post-upgrade)
      run: sqlite3 --version

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with nose2
      run: |
        coverage run -m nose2 --quiet tests
        coverage lcov -o cover/coverage.lcov

    - name: Coveralls
      uses: coverallsapp/github-action@master
      continue-on-error: true
      with:
        path-to-lcov: cover/coverage.lcov
        github-token: ${{ secrets.GITHUB_TOKEN }}
